language: python
python:
  - '2.7'
install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install scikit-learn
script:
  py.test -v -rs --doctest-modules --pep8 --cov whatami --cov-report term-missing whatami
after_success:
  coveralls
notifications:
  email: false
