language: python

python:
  - '2.7'
  - '3.4'

before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda config --set always_yes yes
 - conda update conda
 - conda install scikit-learn
 - conda install future
 - conda install pytest
 - conda info -a
 - travis_retry conda create -n test python=2.7 pip pytest numpy scipy scikit-learn
 - source activate test
 - travis_retry pip install arpeggio pytest-cov pytest-pep8 coveralls

script:
  py.test -v -rs --doctest-modules --pep8 --cov whatami --cov-report term-missing whatami

after_success:
  coveralls

notifications:
  email: false
